Handle sqlite files separately during table/index creation  (#1140)
Sqlite files are now not included in the cached table; this means that
label updates are instantaneous as they would be with
LILAC_USE_TABLE_INDEX=false.

Some resulting changes:
- sqlite files are considered separately in cachebusting logic
- type of `t` switches from TABLE to VIEW, causing various duckdb
errors. As a result...
- new generic try-catch to handle all sorts of migration/transition
errors.

Users may see errors in their logs like

```
Exception: Catalog Error: Table with name cache_t does not exist!
Did you mean "t"?
Exception encountered while updating joint table cache; recomputing from scratch.
Recomputing table+index for $DATASET... took 0.154s.
```

or 
```
Catalog Error: t is not an table
```